project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "Presentation Template"
  navbar:
    left:
      - href: presentation.qmd
        text: Presentation
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

